services:
  next:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
